### ISSUE TITLE
Markdown for "legends" and "descriptions".

### ISSUE THREAD

**Issue by michael-newsrx** [gabrieljohndusing/NCNW-Project-Datasets#1]
Should we switch to using mark down for the legend, report, variables, and group description files?

**Comment by gabrieljohndusing** [comment]
Would it be possible to do both?

**Comment by michael-newsrx** [comment]
Yes. Creating both the existing CSV format for legends, etc, and adding a Markdown formatted version for formatted display via github is possible.

**Comment by gabrieljohndusing** [comment]
Please go ahead and do that. I'd like to be able to quickly review the
legend on GitHub, and to access the legend csv while working on it in
Python. Thanks!

**Comment by michael-newsrx** [comment]
markdown implemented as part of data export procedure.

examples: 

* [acs_1_year_subject_tables-2018.md](https://github.com/gabrieljohndusing/NCNW-Project-Datasets/blob/master/data-sets/census/us/groups/2018/acs_1_year_subject_tables-2018.md)
* [acs_1_year_profile_tables-2018-GROUP_DP02PR_LEGEND.md](https://github.com/gabrieljohndusing/NCNW-Project-Datasets/blob/master/data-sets/census/us/data/2018/legend-md/acs_1_year_profile_tables-2018-GROUP_DP02PR_LEGEND.md)
